### ISSUE TITLE
Build Alpha VF

### ISSUE THREAD

**Issue by davelab6** [clauseggers/Playfair#20]
I'd like to get an alpha VF TTF to help with some engineering testing.

I noticed that the `Playfair-2*.glyphs` files have `opsz` data from 0 to 1000, but I would like to have them use pt values.

My GlyphsApp would not build the TTF VF, from GlyphsApp `File > Export > GX` or fontmake, due to lots of errors.

I need the font to build reliably with fontmake, and recommend setting up the masters and instances correctly now, and complete planned glyph sets even if glyphs are empty or just have a notdef component placed manually, so that the build iterations are simply adding/refining glyphs and other aspects of the project, but it stays in a buildable state constantly :) 

Here's the fontmake errors for Roman: 

```
fontTools.feaLib.error.FeatureLibError: github.com/clauseggers/Playfair-Display/sources/master_ufo/Playfair-DisplaySemiCondensed.ufo:1000:1064: "hook-cy" is not a glyph in the font, and it can not be split into a range of known glyphs
```

and Italic:

```
AssertionError: Location for axis 'Weight' (mapped to 1300.0) out of range for 'Playfair Display SemiCondensed' [400.0..900.0]
```

Full output: https://gist.github.com/davelab6/dee5f221f4a6566a9767bda96bd9508b

**Comment by MarkFonts** [comment]
Hi @clauseggers I’m interested in the status of Playfair as a VF and I’d also love to talk about its design soon.

Feel free to reach me on twitter @MarkFonts
