### ISSUE TITLE
Interpolation Issue In Asterisk

### ISSUE THREAD

**Issue by AutismIsMySuperpower** [clauseggers/Playfair#33]
![Screenshot (64)](https://user-images.githubusercontent.com/92538982/154879834-ec69a443-d121-4b55-942c-af7664f4ea49.png)
This is in Playfair-2-Roman.glyphs and Playfair-2-Italic.glyphs.

**Comment by clauseggers** [comment]
Playfair 2 is not released yet so why are you posting bug reports? Are you that stupid?
