### ISSUE TITLE
Disappearing and reappiring features on different axis

### ISSUE THREAD

**Issue by alarcondgtuc** [clauseggers/Playfair#35]
I'm not a type designer, so I'm not sure if it's a feature or an intentional design choice, but why are some features appearing and disappearing when changing axis? Mainly with optical size

https://user-images.githubusercontent.com/78399996/168491488-54187b1d-9c7f-40ef-bd3c-0eef76f859fb.mp4

Same happens with the Italics version

https://user-images.githubusercontent.com/78399996/168491609-dd3427a9-a2e0-41c0-9db2-97a845db8adb.mp4

**Comment by alarcondgtuc** [comment]
Also, the Minus mathematical glyph is the same as the Dash glyph

**Comment by clauseggers** [comment]
The changing glyphs are contextual switching happening. This is a feature, not a bug. The hyphen, en-dash, and minus glyphs are correct.
