### ISSUE TITLE
Design space location of the original Playfair Display?

### ISSUE THREAD

**Issue by davelab6** [clauseggers/Playfair#39]
I assumed that 2-3-4 (×2 for italics) of the masters in the current design space would be 1:1 with the original Playfair Display masters, but it seems this is not the case. Do you have a recommendation for the design space location that best matches the original static fonts? 

I ask because I would like to upgrade the original family in the Google Fonts API so that it's a 1:1 with the new Playfair family, and makes it easy for users to upgrade from the original to the new.

However, for that upgrade to go smoothly, the new instances should be very close to the originals, ideally with the same metrics

**Comment by clauseggers** [comment]
Well, Playfair 2.0 is an entirely redesigned affair. Everything has been redesigned. Go with opsz:42,wght:400,wdth:88 for the replacement.

NB: The definition of ‘Display’ in Playfair 2.0 has nothing to do with ‘Playfair Display’ and how that was proportioned.
