### ISSUE TITLE
wght 600; wdth 50; opsz 1200 rendering / interpolation issues 

### ISSUE THREAD

**Issue by vikagrabowska** [clauseggers/Playfair#42]
Hi Claus @clauseggers!

I've been looking at Cyrillic in large optical size and noticed a few interpolation bugs that don't seem to relate to the drawings in masters, but which do seem to occur in the interpolation. I checked if they appear in Samsa and Dinamo Font Gauntlet as well, and they seem to be present.

Among them are Zhe-cy, Zhedescender-cy, Ka-cy, Kadescender-cy zhe-cy.smcp, zhedescender-cy.smcp, ka-cy.smcp, kadescender-cy.smcp top arms. However there are also in and out strokes in Cyrillic (and Latin) letterforms. I'm attaching my screenshots.
<img width="1892" alt="Pasted Graphic 10" src="https://github.com/clauseggers/Playfair/assets/78556166/2349828f-f7db-4040-ae5d-135025a55f14">

<img width="1172" alt="Pasted Graphic 12" src="https://github.com/clauseggers/Playfair/assets/78556166/82c442ad-593c-4f16-a657-a5ef27026462">

<img width="1167" alt="Pasted Graphic 11" src="https://github.com/clauseggers/Playfair/assets/78556166/16348043-e5dc-4fe1-9660-f33e47c6a838">

<img width="808" alt="Pasted Graphic 8" src="https://github.com/clauseggers/Playfair/assets/78556166/8cdacac2-f794-469e-bcd3-d0501b973faf">

<img width="801" alt="Pasted Graphic 9" src="https://github.com/clauseggers/Playfair/assets/78556166/a058ec6e-ca28-425a-9516-14863f6e3a44">

<img width="942" alt="Pasted Graphic 13" src="https://github.com/clauseggers/Playfair/assets/78556166/2ef62312-14b5-466f-b197-ee1d346f46fd">

<img width="729" alt="Pasted Graphic 14" src="https://github.com/clauseggers/Playfair/assets/78556166/427e97b7-cb96-4220-80c3-c951ad2401f5">

<img width="1044" alt="Pasted Graphic 15" src="https://github.com/clauseggers/Playfair/assets/78556166/6c516a4f-b706-4ae7-a878-8577df160a63">

<img width="542" alt="Pasted Graphic 16" src="https://github.com/clauseggers/Playfair/assets/78556166/482ac60c-211d-4b79-aec7-65d9f9236f48">

Best,
Vika

**Comment by clauseggers** [comment]
I had a real good look, and most of them are rounding errors. I suspect browsers are causing these issues.
The actual issues were the Cyrillic UC you listed and the Roman and Italic y, and they have been fixed.
