### ISSUE TITLE
б tail in italics

### ISSUE THREAD

**Issue by vikagrabowska** [clauseggers/Playfair#43]
Hi Claus,

In Playfair romans the movement of -б tail seems to be rather soft and calm / slow in its movement which in my view matches the overall rhythm wonderfully.

In italics the the tail of -б seems to be quicker and more rapid in its movement than in roman -б, but also in comparison to the gestures of another Italic letterforms. 
This is a minor letter shape suggestion. There is absolutely nothing wrong with it Cyrillic-wise, it is only a matter of rhythm. But I was wondering if you would be interested in considering a calmer tail in Italic? The situation is consistent across optical sizes, however catches my eye more in larger optical sizes, than in the smallest one (opsz 5). 

<img width="2155" alt="image" src="https://github.com/clauseggers/Playfair/assets/78556166/a5608e92-6dad-420f-83e5-c3327f624ddf">

**Comment by clauseggers** [comment]
Not with you this one either. The Italic б looks fine to me.
