### ISSUE TITLE
Opsz 5 Cyrillic LC, single letterforms observations 

### ISSUE THREAD

**Issue by vikagrabowska** [clauseggers/Playfair#44]
**Italic, wght 360, opsz 5** 

- л skeleton in Italics creates a rather narrow counter for this letter across all the widths. I am wondering if it can benefit from a slight widening? 

Two observations below were actually made in rather big type size, so they might not be relevant for the small optical size. These letters are not bothering my eye in small type setting. 
 
- In Italic г and ж seem to have significantly larger weight than other letters. б on the other hand seems rather light. 
- in Roman descenders such as in ц, д, щ seem to have more weight compared to everything else. 
<img width="2148" alt="image" src="https://github.com/clauseggers/Playfair/assets/78556166/d81102ef-ec58-4dc0-be25-055ec1d13162">

**Italic, wght 900, opsz 5** 

- ф, ж appear slightly dark. The impression of dark ф becomes softer in the wdth 150 (column 6 on the screenshot).
- I wonder if the bellies of ы, љ, њ, ѣ can become slightly higher and as a result brighter. This question appear already in wght 360, but is more present in wght 900.

<img width="2151" alt="image" src="https://github.com/clauseggers/Playfair/assets/78556166/7ba3a73f-9522-4d44-a02c-ec95331c3b1c">

**Comment by clauseggers** [comment]
Italic Agate ф and ж lightened. Italic Agate г and ж had another axis than the rest of the Italic glyphs, hence their deviating appearance. As you rightly note the Agate renderings were too dark, so I harmonised these masters with the rest of the glyphs.
