### ISSUE TITLE
Opsz 5, roman / italic relation

### ISSUE THREAD

**Issue by vikagrabowska** [clauseggers/Playfair#45]
**wght 360; wdth 50-150; opsz 5**

- While comparing paragraphs 3 and 6 from the screenshot below I have an impression that italic in wdth 150 is narrower than roman in wdth 150 in its drawings. This difference in proportions seems to be more noticeable than in wdth 50 (paragraphs 1 & 4) and wdth 100 (paragraphs 2 & 5).
 - italics seem to be spaced more loosely than romans. This impression appears across whole range of widths, but becomes stronger in wdth 150.
 
<img width="2139" alt="image" src="https://github.com/clauseggers/Playfair/assets/78556166/06d8710a-823e-4ee2-aff6-22c4e77ebf28">

**wght 900; wdth 50-150; opsz 5**
 - The impression of italics being spaced more loosely than romans, and as a result being brighter and wider in text than romans becomes stronger here. It is the most present in the widest wdth 150, which is probably a result of longer in and out strokes. 

<img width="2157" alt="image" src="https://github.com/clauseggers/Playfair/assets/78556166/19ec7a4c-537f-4449-a353-8a8da9dbaaac">

The wide spacing of the italic makes a lot of sense for the this small optical size. Perhaps it is actually the roman which could be spaced more widely in the small optical size to better match the italic? The wide spacing for roman might be appropriate for the nominal very small small opsz 5, but the change might influence the interpolated text size in the unwanted way. 

I've been looking at the roman / italic relation through optical sizes in order to see how far this issue reaches. I can still see it in opsz 10.

<img width="2150" alt="image" src="https://github.com/clauseggers/Playfair/assets/78556166/2fac2bbc-2b02-461a-a933-f85426ca20e0">

<img width="2147" alt="image" src="https://github.com/clauseggers/Playfair/assets/78556166/2b121a97-1a3c-41ec-806f-bbd926285fbf">

In opsz 20 I think the spacing thing is only noticeable in wdth 150. Aso proportions of drawings in italic seem perhaps a little narrower than I would expect in comparison to the roman.

<img width="2150" alt="image" src="https://github.com/clauseggers/Playfair/assets/78556166/a42641c2-6273-4ee7-a79c-51f60aee8b0f">
<img width="2133" alt="image" src="https://github.com/clauseggers/Playfair/assets/78556166/820bfc66-1b41-4c72-aa39-0dc49b80da2a">

**Comment by clauseggers** [comment]
Not with you on that one.
