### ISSUE TITLE
Letter -w preview error

### ISSUE THREAD

**Issue by vikagrabowska** [clauseggers/Playfair#46]
This is an issue in preview of -w I can see across whole design space in Samsa, Dinamo Font Gauntlet and Octopus tools. The letter -w lacks the white space inside the loop.
<img width="656" alt="image" src="https://github.com/clauseggers/Playfair/assets/78556166/06352725-af09-4a74-bf28-bd5ca02a8bba">

Here is a preview from Glyphs with an existing  the white space. 
<img width="690" alt="image" src="https://github.com/clauseggers/Playfair/assets/78556166/4ea7d8bd-1197-43a1-abfe-c9429767552e">

**Comment by clauseggers** [comment]
Hi Vika
I’m working on the others, but I can tell you that this one is intended to be this way – that is, the first image is the unused extrema of the special alternate for the Agate, hence it will never be seen.

**Comment by vikagrabowska** [comment]
Hi Claus,
Thanks for getting back to me so quickly and clearing things up, I see what you mean now.
Best,
Vika
