### ISSUE TITLE
Support of DIN 91379 (Unicode subset for Europe)

### ISSUE THREAD

**Issue by vk-github18** [clauseggers/Playfair#49]
# Support of DIN 91379 (Unicode subset for Europe)
Please support all letters and sequences of DIN 91379 "Characters and defined character sequences in Unicode for the electronic processing of names and data exchange in Europe"

## Current rendering
Some letters and diacritics are missing or positioned incorrectly.
(Rendering using 
  hb-view (HarfBuzz) 2.8.1 
  Ubuntu 22.04.2 LTS)

[latin_letters_all_PlayfairRomanVF.pdf](https://github.com/clauseggers/Playfair/files/12208949/latin_letters_all_PlayfairRomanVF.pdf)
[latin_list_all_PlayfairRomanVF.pdf](https://github.com/clauseggers/Playfair/files/12208950/latin_list_all_PlayfairRomanVF.pdf)

## Rendering with Arimo
[latin_letters_all_Arimo-Regular.pdf](https://github.com/clauseggers/Playfair/files/12208951/latin_letters_all_Arimo-Regular.pdf)
[latin_list_all_Arimo-Regular.pdf](https://github.com/clauseggers/Playfair/files/12208953/latin_list_all_Arimo-Regular.pdf)

## See also
- https://github.com/String-Latin/DIN-91379-Characters-and-Sequences List of characters and sequences of DIN 91379
- https://en.wikipedia.org/wiki/DIN_91379

**Comment by clauseggers** [comment]
How would you like to be invoiced?

**Comment by clauseggers** [comment]
Listen here Volker. Don’t open random requests on people’s repositories asking for years of work to be done, and then when challenged be a coward and leave a thumbs down. I don’t know if you have rocks or porridge in your cranium, you’ll have to decide that for yourself.
