### ISSUE TITLE
VF instances opsz axis values seem wrong

### ISSUE THREAD

**Issue by Cogli** [clauseggers/Playfair#51]
Hi,

I just downloaded the last release for [playfair VF](https://github.com/clauseggers/Playfair/blob/58a0cedfa53424d4c31175bace064ca0f98c0037/fonts/VF-TTF/PlayfairRomanVF.ttf), and opsz axis value for the various instances doesn't seem to coincide with the static files. For instance, miniature is set at 325.
![immagine](https://github.com/clauseggers/Playfair/assets/55837580/c1e8665e-a5f1-41cc-a9b0-45efa3227684)

Thanks for Playfair!

**Comment by clauseggers** [comment]
Hi there. Which website did you use to produce the screenshot?

**Comment by Cogli** [comment]
https://wakamaifondue.com/

Same for InDesign 17.0.1 on windows 11, and for https://fontgauntlet.com/

**Comment by clauseggers** [comment]
I just tried it fountgaultlet, and in Safari/MacOS the optz axis is broken. Works somewhat better in Chrome/MacOS though. There the opsz axis actually works, but the mapping of the named instances is broken save for the `micro` size. This looks very much like a Glyphs bug. I will take it up with the Glyphs people. Thank you for reporting this.

**Comment by clauseggers** [comment]
@Cogli I found the error and fixed it. You can download the update font binaries here: https://github.com/clauseggers/Playfair/releases/tag/2.100-RC-3

**Comment by Cogli** [comment]
Great, thank you!
