### ISSUE TITLE
IPA and GF Latin SSA

### ISSUE THREAD

**Issue by moyogo** [clauseggers/Playfair#52]
Several Latin African orthographies are based on the International African Alphabet, published in 1927 and in the 1930 *Practical Orthography of African Languages*, which is directly derived from the IPA of the time. The IPA has slightly evolved since but there are no major relevant differences.

## Samples from the *Practical Orthography of African Languages*

The style used in *Practical Orthography of African Languages* may useful.

Notes:
- /A/a in italic are confusable with /Alpha-latin/alpha-latin from a later General Alphabet of Cameroon Languages (also borrowing from IPA). In Playfair, /a/alpha-latin need to be distinct. One solution is to have /alpha-latin as a more traditional Greek-like alpha with not vertical stem but the in-stroke of the loop crossing the out-stroke of the loop, with a hook terminal on the out-stroke. Unicode does not distinguish between IPA’s script-a and GACL’s Latin alpha, as both sometimes have the other’s shape. Alternatively, the /a could have an alternate slanted shape, this is not common but can be useful.
- Ɓ had the shape of Latin Ƃ /Btopbar or Б /Be-cy. The B-shape is used instead nowadays, except in Liberia where the Ƃ-shape is still used. **locl** variant Bhook needed for Toma `TOD0`, Dan-Gio `DNJ `, Kpelle Liberia `XPE ` language systems.
- Ə and ə are used here and are still used in several language orthographies. In some countries, the Ǝ and ǝ are used instead. No locl feature is required in this case.
- ƒ needs to be different from f in italic in Ewe `EWE `, Avatime `AVN `, Lelemi `LEF `, Waci Gbe `WCI ` language system. The ƒ and f are already good for these languages in Playfair. If that wasn’t the case an alternate /f would be needed for the **locl** feature in those language systems. Keep in mind that English, French or other languages used in the countries where those languages are used may have borrowed words or proper names with ƒ. So either the default f needs to not have a hook, or at least a ssXX or cvXX feature needs to also provide the alternative f without hook.
- Ŋ had and still most often has the n-form instead of the N-form in African languages. However while the n-form is often preferred by editors, readers don’t seem to care either way. So depending on the style, both may not be necessary, especially when one hardly fits. In Playfair both seem to fit. The n-form can be the default as there is a larger number of languages that use that form, several of which do not have an OpenType Language System Tag, and the N-form should be the **locl** variant for Northern Sami `NSM ` or other Sami languages which may use it in borrowed names: Inari Sami `ISM `, Lule Sami `LSM `, Skolt Sami `SKS `, Souther Sami `SSM ` -- it’s not clear for `KSM ` as it used the n-form in the 1930s -- or other adjacent languages (Swedish, Norwegian, Finnish).
- Ʃ had the shape of Greek Σ /Sigma, the ʃ-shape (or Cyrillic  Ꚃ-shape) is used in the Gabon Scientic Alphabet reference and the Guine National Alphabet reference. **locl** variant Esh  Greek Σ-shape could be added for the Ga `GAD `, Xhosa `XHS `, Zulu `ZUL ` language systems that used it between the 1930s and the 1950s or 1960s.
- Ʋ /Vhook had a squarish shape. The shape nowadays is more round like the ʋ /vhook. In Playfair the ʋ /vhook will be confusable with /v. In some works of the period, /vhook has a closed loop. The **locl** variant with an angular-v shape and an above-x-height hook is used in the Toma `TOD0`.
- Ʒ had the shape of a reversed Greek Σ /Sigma, it has a baseline large ʒ-shape nowadays instead. The old shape is not needed. The a reversed Greek Σ shape could be added for the `GAD ` language system.
- the bold has some issues in this work:
  - ɓ /bhook has its hook too high, the regular is good
  - ɣ /gamma-latin is a bit out of balance, the regular looks better

IPA consonants and vowels (only lowercase, note ɬ and ɮ are only used as IPA symbols)
![Practical Orthography of African Languages](https://github.com/clauseggers/Playfair/assets/1923747/079df30a-fdef-4d5d-849f-6c2fd13342c3)

Capital letters and written forms.
![Practical Orthography of African Languages 1](https://github.com/clauseggers/Playfair/assets/1923747/bb01bc17-911a-49a8-807e-2778d4db0fa4)
Alphabetical order of the letters
![Practical Orthography of African Languages 3](https://github.com/clauseggers/Playfair/assets/1923747/85778f2e-c65b-4ffa-87ab-409c09c690ed)

## Samples from *The New Script* 1930
See https://archive.org/details/the-new-script-and-its-relation-with-the-languages-of-the-gold-coast

This shows a lot of letters with a modern style.

Notes:
- There no appropriate Ɛ.
- The Ga Ʒ ʒ /Ezh/ezh and Ʃʃ /Esh/esh have been replaced by J j and digraph Sh sh in the 1960s.

## Sample from A. Burssens & G. van Bulck, "De Africa-spelling en de Kongoleesche talen", *Kongo-Overzee*, vol. 2, no. 2,‎ December 1935, p. 65-93

(sorry for quality)

- These are lowercase, directly from the same type as used in *Maitre Phonétique*, the journal of the IPA.
- ɑ /alpha-latin has a script-a shape. It’s not clear the authors intended to use italic at all.
- ꭓ /chi-latin is raised by mistake. In any case, the letter isn’t used in African orthographies but was or may used in phonetic transcriptions. It’s not SSA so don’t worry about it.
- ʔ /glottalstop is a cut question mark. This should be avoided and the letter should be drawn from baseline to ascender-height.

<img width="504" alt="Screenshot 2023-11-08 at 15 17 38" src="https://github.com/clauseggers/Playfair/assets/1923747/f2cffc5e-6459-4252-8eb1-d865cc5216fc">

## Samples from UNESCO Niamey meetings 1978

See https://unesdoc.unesco.org/ark:/48223/pf0000060064

These aren’t super useful for Playfair but are still an important reference for letter identity.

<img width="969" alt="Screenshot 2023-11-08 at 15 36 20" src="https://github.com/clauseggers/Playfair/assets/1923747/a940dbcd-4a9b-407b-a774-06a4d6bea8a9">

Notes:
- Several shapes are poorly designed (like Ɛ being a cut reversed B, or Ɣɣ or Ʊʊ or ʒ).
- Here ɑ /alpha-latin and Ɑ /Alpha-latin do not have the script-a form but are closer to the loop-form in some way.
- The special /Eth nor /eth are used in Latin African orthographies so it can be ignored.
- The hooks on ƁƊƘƳ /Bhook/Dhook or /Khook/Yhook are mild or slightly off, they should be better defined and more pronounced.
- Ƒ /Fhook has a centered crossbar but no hook. This should be avoided, it should have a bottom hook (on the baseline or below).
- Ɩ ɩ have the shapes of Ɪ ɪ as IPA used both ɩ and ɪ as alternates of the same symbols for a while. Nowadays they are distinct. Ɩ ɩ should be distinct from iıl /i/idotless/l in particular in italic. The hook terminal of Ɩ ɩ can be more pronounced, like a milder reversed J and milder reversed ᴊ in italic. The distinction is less needed in roman in some styles, like Playfair roman styles.
- Ʈ /Tretroflexhook has a peculiar Ŧ-shape instead of a T-shape with a bottom right hook, like ʈ /tretroflexhook. This should be avoided, the T-shape with a bottom right hook is more appropriate. This letter is rare or not used in orthographies, it still need to do some research on its current use.
- The z with hook isn’t used in orthographies and hasn’t been encoded in Unicode. It can be ignored.
- The Ʃ has the ʃ-shape (like in the Gabon Scientific Alhpabet and the latest Guinea National Alphabet).
- Ʋʋ are boxy but this can work with the style.

## Turned letters
Turned letters are not necessarily turned (also in IPA), these are actually nicer: ɥ /hturned can be a u with a q-terminal, ɯ /mturned can be a u-u ligature, ʌ /vturned can be angular even when v is round.

## Ismall and its capital
Ɪ ɪ is used in at least on language in Côte d’Ivoire. Historically it’s a variant of Ɩ ɩ, at least ɪ and ɩ being variants in IPA as mentionned above.

Like in IPA, ɪ /Ismall should be noticeably distinct from i or ı. That seems straightforward in Playfair, the serif can still be slightly more pronounced on ɪ /Ismall.
The capital /uniA7AE should have top and bottom bars instead of serifs. It’ a bit of a Frankenstein letter, it can be built from a narrow T and turned narrow T.

## Vhook
Regarding the /vhook/v issue, in *Le Maître phonétique*, April-June 1932, p. 34, two solution are presented.
<img width="941" alt="f463b9067b400dde" src="https://github.com/clauseggers/Playfair/assets/1923747/ed400531-0393-4138-9731-69469ff45cbf">

Here it is in print in Clement M. Doke, *English-Lamba Vocabulary*, 1933
<img width="962" alt="Screenshot 2023-11-08 at 14 54 12" src="https://github.com/clauseggers/Playfair/assets/1923747/98f800d2-e085-4f23-8d02-5837a72795a1">

This solution seems to not have been used recently, rather the distinction is made with angular-v for /v and round-v for /vhook.
Since Playfair has a round-v for /v, one could consider this old form as a solution.

Alternatively, in italic, the /vhook could have a hook in-stroke terminal (like i, n, etc.) and a shape closer to a slanted roman.

Note the Toma `TOD0` locl variant with the angular-v shape and above-x-height hook mentionned above likely wouldn’t work in several languages as in many cases /vhook is used as a vowel (due to its similarity with Ʊ ʊ /Upsilon-latin/upsilon-latin).

# ramshorn and capital
ɤ /ramshorn is used in two languages in Côte d’Ivoire and the capital uniA7CB will be in Unicode 16 this year. Both should be distinct from Ɣɣ /Gamma-latin/gamma-latin. The IPA symbol ɤ used to be a "baby-gamma" (small capital Ɣ on the baseline) but since 1989 it has hook terminals on both in- and out-strokes.

**Comment by clauseggers** [comment]
Denis do you have the alphabet for each of the languages we are doing?

**Comment by moyogo** [comment]
Yes, 579 of them with 130 which I updated with sources.

Do you need all of them in a specific format?
They are in [gflanguages](https://github.com/googlefonts/lang).

**Comment by clauseggers** [comment]
I need some of them populate my test documents. Looking at the sheer number of languages I should probably start with a dozen of them. I would need sample texts/corpus for each. Can you recommend such a short list?

**Comment by moyogo** [comment]
aɑ: italic a and ɑ are identical, italic ɑ should be distinct from a. They are both used in a few Cameroon languages like [Feʼfeʼ](https://en.wikipedia.org/wiki/Feʼfeʼ_language) or [Medumba](https://en.wikipedia.org/wiki/Medumba_language). There are two options: design ɑ /alpha-latin more distinctly (more Greek-like, starting from top right, loop, ending bottom right) and/or have a slanted form of a as a stylistic variant if possible.

ꞵ: italic could have bottom serifs like p and others at opsz=5.
<img width="340" alt="Screenshot 2024-07-03 at 12 26 35" src="https://github.com/clauseggers/Playfair/assets/1923747/d6cb05cf-155a-4f7d-a479-80e2a720d136">

Ɩ and l, or ɩ and ı (idotless) are too similar, particularly in italic. Some sans serif fonts have a half-circular bottom hook. A similar 19th century English Phonotypic Alphabet i with hook had a drop-terminal hook to make it more distinct from i. Possibly the bottom hook terminal of ɖ ɋ ɽ ʈ, or a less prominent form of it, could be used on the baseline. The defining feature of the letter Latin iota is the bottom terminal, the top terminal can vary just like that of i (curved terminal, left serif, or naked stem). ᶥ /iotamod should be updated likewise.

|   |   |
| -- | -- |
| <img width="340" alt="Screenshot 2024-07-03 at 12 27 41" src="https://github.com/clauseggers/Playfair/assets/1923747/57095f65-14b9-4625-9544-71cb20821649"> | <img width="340" alt="Screenshot 2024-07-03 at 15 27 18" src="https://github.com/clauseggers/Playfair/assets/1923747/42188e44-0f9e-455b-9ecf-34971b66c484">
| <img width="340" alt="Screenshot 2024-07-03 at 15 27 27" src="https://github.com/clauseggers/Playfair/assets/1923747/d99c62c0-dfde-4a48-b81d-7df30edfbd70"> | <img width="340" alt="Screenshot 2024-07-03 at 15 27 29" src="https://github.com/clauseggers/Playfair/assets/1923747/36b17824-6991-492b-a0f0-027cc87d144e">

For example with the hook tail from ɖ ɋ ɽ ʈ:
|   |   |
| -- | -- |
| <img width="340" alt="Screenshot 2024-07-03 at 15 28 36" src="https://github.com/clauseggers/Playfair/assets/1923747/e4b3dc99-3c6c-4ae9-bad9-8294ba4aebac"> | <img width="340" alt="Screenshot 2024-07-03 at 15 29 54" src="https://github.com/clauseggers/Playfair/assets/1923747/212c61f4-323c-4d7c-ba2b-f5067277ec7a">
| <img width="340" alt="Screenshot 2024-07-03 at 15 30 01" src="https://github.com/clauseggers/Playfair/assets/1923747/cae044bd-bc6e-4726-8279-d35e74a2295a"> | <img width="340" alt="Screenshot 2024-07-03 at 15 30 34" src="https://github.com/clauseggers/Playfair/assets/1923747/50c0ee99-007f-4b5b-90a6-a985a4bc0979">

Ɥ is square, it’s better to use the same shape or a shape similar to Ч in both roman and italic.
In the [character Unicode proposal](https://www.unicode.org/L2/L2008/08182r-latin-cyr.pdf), the shape of Ɥ is as the uppercase of ɥ on page 3. See Doulos SIL and Charis SIL

<img width="203" alt="Screenshot 2024-07-03 at 15 38 10" src="https://github.com/clauseggers/Playfair/assets/1923747/de311ab2-4cc6-4e8b-b18d-8d24d3804266">

See for example Tucker 1929 which uses the letter:
<img width="600" alt="A. N. Tucker, 1929" src="https://upload.wikimedia.org/wikipedia/commons/d/db/A._N._Tucker_proposed_Sotho-Tswana_alphabet_-_1929.png">

ʌ: italic ʌ could be like like a cursive small-cap A without stroke, somewhat similar to italic л in some other fonts (with sharp top instead of round).
But all three shapes are fine, so you can keep it as is if you prefer.

Ꞷ may be better without the loop (mid & high opsz) as a Initial Teaching Alphabet makes the distinction between omega and omega with loop as two separate letters (Unicode only has omega at this time). The same is true for the small-cap.

ƘⱲƳ (or small-caps) and ƴ:
- ƘƳƴ are good in italic, but italic Ⱳ should have a hook similar to ƘƳ.
- The italic ƳY and ƴy are distinct enough. For roman, the hook on y could be more pronounced (more similar to its bottom hook, that of f, or hook in italic), it works as currently in most sizes and a change would mostly help at very small sizes.
- The flat hook of roman Ƙ /Khook takes more space which helps keeping it distinct from /K. The flat hook of roman Ƴ /Yhook could be more pronounced. The roman ƘⱲƳƴ could have rounder hooks like in italic.
  For example, Ƙ in the 1960s
  <img width="328" alt="Ƙoƙi - 10 1017:S0041977X0012419X_" src="https://github.com/user-attachments/assets/fdbb506f-aa62-4a8f-9022-5b0ff9ddc92f">


ƭ: should not be descending in italic.

Ɲ: can have n-shape or N-shape like Ŋ. Some orthographies use them together. Maybe make them consistent (even if not consistent with N). Or have alternate available if possible.

ʋ: italic should be distinct from v (low opsz). Since v won’t change to an angular v at this point, ʋ shouldn’t have a long in-stroke ; I guess the layers were copied but should be removed.The hanging ball, may be a good solution to make it more distinct. Another solution would be to have an almost closed loop with a narrow terminal.
<img width="123" alt="Screenshot 2024-07-19 at 01 33 37" src="https://github.com/user-attachments/assets/3f1cec99-956d-45f5-b061-b46b37ea2cd1">

Ⱥ ⱥ Ȼ ȼ Ɇ ɇ Ø ø Ⱦ ⱦ Ꞹ ꞹ: they are used together in some orthographies. Having different angles or lengths of the stroke is fine if necessary. The same is true for small-caps.
<img width="958" alt="Screenshot 2024-07-19 at 01 35 47" src="https://github.com/user-attachments/assets/72508bf2-b51f-47d8-909d-ef0c664d900a">

ʔ ɂ ʕ are missing small-caps. Ɂ is good.

Ɛ: italic /E.ss02 and Ɛ could actually be the same glyph, both are good shapes for Ɛ. The same goes for /e.smcp.

Ɇ ɇ: italic /Estroke and /estroke.smcp could also have ss02 variants.

ƴ: /yhook could have a ss06 variant.

Ⱦ: /Tdiagonalstroke could have a ss07 variant like Ŧ /Tbar/Tbar.ss07.

Consider adding:
Ɤ /Ramshorn or /uniA7CB, capital of ɤ /ramshorn (used in Côte d’Ivoire).
ꟛ: add /lambda-latin or /uniA7DB as ƛ /lambdastroke without stroke (used in Canada).
ꟚꟜ: /Lambda-latin/Lambdastroke or /uniA7DA/uniA7DC as capitals of ꟛƛ, shaped like turned Y and turned Y with diagonal or horizontal stroke (used in Canada). The current preference is diagonal in the Heiltsuk community that asked for character in Unicode. It’s not clear if the historical horizontal stroke they have also used is currently preferred in one other community using the capital letter. Italic would have to have the shape of slanted turned Y, as italic turned Y wouldn’t work.

**Comment by clauseggers** [comment]
From which application did you take the screenshots like this one?
<img width="340" alt="345384929-d6cb05cf-155a-4f7d-a479-80e2a720d136" src="https://github.com/user-attachments/assets/cbb78f74-5c1d-4749-9ca9-d2e06275201a">

**Comment by clauseggers** [comment]
Is there a model of the Ramshorn (A7CB) glyph somewhere?

**Comment by clauseggers** [comment]
Here is an interesting question about the latinised Lambda: Do I follow the reversed contrast of the LC, or do I use the Latin style?
<img width="759" alt="Screenshot 2024-07-31 at 13 44 31" src="https://github.com/user-attachments/assets/df079b59-5813-4a7c-8e54-d0a171ad4fbb">
<img width="690" alt="Screenshot 2024-07-31 at 13 44 16" src="https://github.com/user-attachments/assets/529cf5c3-b55b-4080-bcdb-758ae15b90ef">

**Comment by moyogo** [comment]
For Ramshorn, the Eastern Dan community has been using a large lowercase. Some SIL fonts: Doulos SIL, Charis SIL, Gentium Plus or Andika, have the PUA character U+F26E for it:
<img width="186" alt="Screenshot 2024-08-09 at 23 36 00" src="https://github.com/user-attachments/assets/30f211ef-cc24-4882-a372-f9949995d53b">

If this helps, a 16th French author had suggested a French orthography using the same or a similar letter using italic:
<img width="431" alt="Screenshot 2024-08-09 at 23 38 47" src="https://github.com/user-attachments/assets/e5406b6c-a9a1-4394-9fda-bcf109f750e9">


For Lambda-latin and Lambdastroke-latin, it is typically a turned Y, without reversing the contrast, but there’s a few documents where it’s more like an inverted Y.
The preference seems to be for the turned Y for the uppercase. See https://www.unicode.org/L2/L2023/23191-three-latin-additions.pdf

**Comment by clauseggers** [comment]
Can I get away with this form of `vhook`? `028B`

<img width="866" alt="Screenshot 2024-08-11 at 12 18 00" src="https://github.com/user-attachments/assets/57d4d8aa-2e6e-4c5c-ad93-68fcb849e179">

I’d like to do the same to the ƴ `01B4` and ⱳ `2C73`, but can see that this would a new and unexpected rendering. What do you think?

On the matter of the Italic form of `iota-latin` `0269` I have tried your suggestion, but it was too disruptive to the word shapes. I have currently reverted to my original form, but I can see that more disambiguation is needed. Work in progress…

**Comment by moyogo** [comment]
For vhook ʋ 028B, it think that could work. The common shape used for roman in Loma language in Liberia is angular with a raised hook, the italic is typically the slanted equivalent. For other regions and languages the round shape is normally used. Having a shape that use idea from both could work.

For yhook ƴ 01B4 there are definitely many examples of it having a raised hook. That should work with whook ⱳ 2C73 as well as the Lobiri and Puguli languages that use whook also use yhook.

**Comment by clauseggers** [comment]
Release 2.2 closes this
