### ISSUE TITLE
Interpolation problems in `PlayfairDisplay[wght].ttf`

### ISSUE THREAD

**Issue by behdad** [clauseggers/Playfair#53]
Hello!

This is an automatically-generated report about possible interpolation problems in `PlayfairDisplay[wght].ttf`, as found in the Google Fonts catalog.

To download a PDF version of this report with helpful visuals of the problems, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/raw/f7909283ad1e65afe43d920bba367832f78f6730/reports/PlayfairDisplay%5Bwght%5D.ttf.pdf); Or to view it on the GitHub website, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/blob/f7909283ad1e65afe43d920bba367832f78f6730/reports/PlayfairDisplay%5Bwght%5D.ttf.pdf).

The report follows:
```
Glyph uni2196 was not compatible:
  Masters: '', 'wght=900.0':
    Contour order differs: [0, 1, 2, 3] in '', [1, 0, 2, 3] in 'wght=900.0'
Glyph uni2197 was not compatible:
  Masters: '', 'wght=900.0':
    Contour order differs: [0, 1, 2, 3] in '', [1, 0, 2, 3] in 'wght=900.0'
Glyph uni2198 was not compatible:
  Masters: '', 'wght=900.0':
    Contour order differs: [0, 1, 2, 3] in '', [1, 0, 2, 3] in 'wght=900.0'
```

This report was generated using the `fonttools varLib.interpolatable` tool.  We understand that sometimes the tool generates false-positives.  Particularly for more complicated font designs.  If you did not find this report useful, please accept our apologies and ignore / close it.

To give feedback about this report, please file an issue or open a discussion at [fonttools](https://github.com/fonttools/fonttools).

**Comment by clauseggers** [comment]
Hello Behdad. You have to point your automatised to Googles fork of Playfair. For the future do *not* report these issues in my repo unless they truly are issues in the canonical Playfair.

**Comment by behdad** [comment]
Noted. Thanks.

**Comment by behdad** [comment]
Sorry to bother you again. I ran the tool against your fonts in the repo and found a couple issues with the Italic. I hope you don't mind me putting them here:
[out.pdf](https://github.com/clauseggers/Playfair/files/13450739/out.pdf)

**Comment by clauseggers** [comment]
Which fonts exactly did you run it on? (NB: Your PDFs should report the exact file they are run on.)

**Comment by behdad** [comment]
> Which fonts exactly did you run it on?

This file: https://github.com/clauseggers/Playfair/blob/master/fonts/VF-TTF/PlayfairItalicVF.ttf

> (NB: Your PDFs should report the exact file they are run on.)

Will work on that. Thanks.

**Comment by clauseggers** [comment]
Weird because I don’t have the issue in the Glyphs file. Perhaps the TTFs were generated using one of the CLI tools, I can’t remember.

**Comment by clauseggers** [comment]
Come to think of it, the PDFs should have all the meta-information available. I would like to see the following:
Full path & filename (and hash where available?)
Branch name.
Font version (and hash where available?)
Generated by info + version (if that exists in the fonts)
Time of PDF generation.

**Comment by clauseggers** [comment]
And how could I forget: GIT BLAME

**Comment by behdad** [comment]
Hi again. Would you mind closing this issue and possibly open another one for the remaining issues you want to address? That way my automated tools won't comment on this issue about updates. Sorry for the inconvenience.

**Comment by clauseggers** [comment]
The issue has not been fixed. It is now Sunday evening, so take a chill pill.

**Comment by clauseggers** [comment]
Hey ho, here we go. The release of Playfair 2.1 closes this issue.

**Comment by behdad** [comment]
Thank you!
