### ISSUE TITLE
v2.100 afrc figure 9 dnom and numr broken in static

### ISSUE THREAD

**Issue by kenmcd** [clauseggers/Playfair#56]
v2.100 afrc figure 9 dnom and numr broken

File: Playfair-Regular.otf (static)

Glyphs: /nine.dnom.afrc /nine.numr.afrc

I was testing the new `afrc` feature and the `7/9` test did not look right.
It appears something happened to the afrc figure nine dnom and numr in the static fonts.

See image below of some of the afrc figures.
I added the /eight.numr.afrc in the preview for size comparison.

![afrc-figure-nine](https://github.com/clauseggers/Playfair/assets/844920/0f3122bf-166b-4d5e-a3e4-ef42c176109e)

**Comment by clauseggers** [comment]
Fixed! Thank you for spotting this one. Please download the 2.101 release.
