### ISSUE TITLE
OpenType math support

### ISSUE THREAD

**Issue by illfygli** [clauseggers/Playfair#57]
Hello, I really like this font, and use it in university work when I can.

It would be really nice if it supported OpenType math, and could be used for mathematical formulae in software like TᴇX or Typst. There's not many beautiful fonts around that can do both.

Maybe that is too big of an undertaking, and/or out of scope; feel free to close if so!

**Comment by clauseggers** [comment]
I’d love to do it but there are serious roadblocks, first and foremost is the lack of a Greek. With Playfair now in three axes and two styles, the Greek would need to be as well. This is a major undertaking that would require major financing.
