### ISSUE TITLE
Google Fonts Static Playfair Fonts

### ISSUE THREAD

**Issue by cmahte** [clauseggers/Playfair#59]
I know this isn't the right spot to report, but maybe Claus knows who. 

The Google Font download has only 9pt and 144pt cuts in it. 

Thank you for providing sane static fonts here. 

But can you nudge the Google fonts edition to also have more rational choices?

**Comment by clauseggers** [comment]
Google does what Google wants. I have no influence over them. By the way: The current statics are the last statics that I will publish. From the next version it is variable font only.
