### ISSUE TITLE
Hash symbol looks like a sharp

### ISSUE THREAD

**Issue by Lamecarlate** [clauseggers/Playfair#61]
Hello, I use Playfair Display in a project. I discovered Playfair 2.1 recently and tested it. I love it, especially the gorgeous ligatures! But there is a tiny problem: the "#" symbol really looks like a "♯".

Examples on my project:

Playfair Display: ![Hash in Playfair Display](https://github.com/user-attachments/assets/50bbf4bc-4051-4eb2-8aab-a30a1fd5d948)

Playfair 2.1: ![Hash in Playfair 2](https://github.com/user-attachments/assets/7c6a85a0-6c1c-4ad9-a4e2-c514009ae44f)

(the global font size seems different too, but that's not an issue)

Is this a forgotten glyph?

**Comment by clauseggers** [comment]
It was changed to give more colour to the very highest contrast masters.

**Comment by Lamecarlate** [comment]
I think I did not explain what is the problem to me: it's not the larger strokes (they're lovely), it's the tilt of the horizontal bars, which are now oblique, that makes the glyph look like a sharp.

**Comment by clauseggers** [comment]
As I just indicated by closing this non-issue with a `not planned` I will not be making changes.
